title: "My GitHub Pages"
description: "This is my personal GitHub Pages website."
baseurl: ""
url: "https://Kimsc9976.github.io"

# Jekyll이 modules 폴더를 포함하도록 설정
include:
  - modules

collections:
  algorithm:
    output: true
    permalink: /algorithm/:path/

# Jekyll이 modules 폴더를 제외하지 않도록 설정
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - modules

# # 카테고리 설정
# collections:
#   algorithm:
#     output: true
#   example:
#     output: true

# # 카테고리 기본 설정
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       categories: helloworld

# # paginate: 5
# # paginate_path: "/page:num/"